name: Test

on:
    workflow_run:
        workflows: [TRAIN]
        types: [completed]


jobs:
  on_success:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion=='success'}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: prateeks71
          password: Seventy1!71
      - name: pull docker image
        run : |
          docker pull prateeks71/asgn3_ps:v1
      - name: run docker image
        run : |
          OUTPUT=$(docker run prateeks71/asgn3_ps:v1)
          echo "SCORE:"
          echo "$OUTPUT"
          if [[`echo "$OUTPUT 0.50" | awk '{print($1 < $2)}'`==1]]; then echo "LESS ACCURACY" && exit 1;
          fi
      - name: Install pytest and run
        run : |
          python -m pip install --upgrade pip
          pip install pytest
          pytest tests/test_score.py


      


                
          