name: Train

on :
  workflow_dispatch:
  pull_request:
    branches: [ "1_2_MAIN" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'

permissions:
  contents: read

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Build Docker image
        id: step1
        run : docker build . -t asgn3_ps:v1
        #continue-on-error: true

      - name: Login to Docker Hub
        id: step2
        uses: docker/login-action@v2
        with:
          username: prateeks71
          password: Seventy1!71
        #continue-on-error: true
      - name: push docker image
        id: step3
        run : |
          docker tag asgn3_ps:v1 prateeks71/asgn3_ps:v1
          docker push prateeks71/asgn3_ps:v1
        #continue-on-error: true  
      #- name: Handle Docker Push Failure
      ##  if: ${{steps.step1.outcome!='success'}} 
      #  # || steps.step2.outcome!='success' || steps.step3.outcome!='success'}}
      #  run: echo "Docker push failed" && exit 1; fi
       
